// src/config/LanguageContext.js
import React, { createContext, useContext, useState, useEffect } from 'react';
import { I18nManager } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

const LANG_KEY = '@snapmathacademy_language';

const STRINGS = {
  // Tabs
  home:        { en: 'Main',       ar: 'الرئيسية' },
  journeyTab: { en: 'Curriculum', ar: 'المنهج' },
  practice:    { en: 'Practice',   ar: 'التمارين' },
  parentsTab:  { en: 'Parents',   ar: 'أولياء الأمور' },
  aiChat:      { en: 'AI Chat',    ar: 'المدرب' },
  profile:     { en: 'Profile',    ar: 'الملف الشخصي' },
  tabHome:     { en: 'Home',       ar: 'الرئيسية' },
  tabPractice: { en: 'Practice',   ar: 'التمارين' },
  tabCoach:    { en: 'Coach',      ar: 'المدرب' },
  tabProfile:  { en: 'Profile',    ar: 'الحساب' },

  // App name (display)
  appName:     { en: 'SnapMath Academy', ar: 'سناب ماث أكاديمي' },
  launchTagline: { en: 'Learn. Master. Stand Out.', ar: 'تعلّم. أتقن. تميّز.' },

  // Common
  back:        { en: 'Back',       ar: 'رجوع' },
  save:        { en: 'Save',       ar: 'حفظ' },
  cancel:      { en: 'Cancel',     ar: 'إلغاء' },
  skip:        { en: 'Skip',       ar: 'تخطي' },
  done:        { en: 'Done',       ar: 'تم' },
  search:      { en: 'Search...',  ar: 'ابحث...' },
  comingSoon:  { en: 'Coming Soon',ar: 'قريباً' },
  next:        { en: 'Next',       ar: 'التالي' },
  getStarted:  { en: 'Get Started',ar: 'ابدأ رحلتك' },
  startNow:    { en: 'Start Now →',ar: 'ابدأ الآن ←' },
  continueBtn: { en: 'Continue →', ar: 'استمر ←' },
  networkServerTitle: { en: 'Server Unreachable', ar: 'الخادم غير متاح' },
  networkServerBody: { en: 'Running in offline mode - your progress is saved locally.', ar: 'يعمل التطبيق الآن دون اتصال، وتقدمك محفوظ محلياً.' },
  networkOfflineTitle: { en: 'No Internet Connection', ar: 'لا يوجد اتصال بالإنترنت' },
  networkOfflineBody: { en: 'Check your Wi-Fi or mobile data.', ar: 'تحقق من شبكة الواي فاي أو بيانات الهاتف.' },
  networkRetry: { en: 'Retry', ar: 'إعادة المحاولة' },

  // Auth
  login:       { en: 'Log In',     ar: 'تسجيل الدخول' },
  signup:      { en: 'Sign Up',    ar: 'إنشاء حساب' },
  email:       { en: 'Email',      ar: 'البريد الإلكتروني' },
  password:    { en: 'Password',   ar: 'كلمة المرور' },
  name:        { en: 'Name',       ar: 'الاسم' },
  forgotPass:  { en: 'Forgot your password?', ar: 'نسيت كلمة المرور؟' },
  resetIt:     { en: 'Reset it',   ar: 'استعدها' },
  noAccount:   { en: "Don't have an account? Sign Up", ar: 'ليس لديك حساب؟ سجّل الآن' },
  hasAccount:  { en: 'Already have an account? Log In', ar: 'لديك حساب؟ سجّل دخولك' },
  demoLogin:   { en: 'Demo Login →', ar: 'دخول تجريبي ←' },
  orDivider:   { en: 'OR',         ar: 'أو' },

  // Onboarding (4-step wizard)
  onbWelcome:    { en: 'Welcome to SnapMath Academy', ar: 'أهلاً بك في سناب ماث أكاديمي' },
  onbWelcomeSub: { en: 'Your personal path to Tawjihi success', ar: 'طريقك الشخصي إلى نجاح التوجيهي' },
  onbGetStarted: { en: 'Get Started',        ar: 'ابدأ' },
  onbStepLogin:  { en: 'Welcome / Log in',   ar: 'مرحباً / تسجيل الدخول' },
  onbStepGrade:  { en: 'Select grade level', ar: 'اختر صفك' },
  onbStepSubjects:{ en: 'Choose subjects',   ar: 'اختر المواد' },
  onbStepFocus:  { en: 'Choose Focus',      ar: 'اختر المواضيع' },
  onbReady:      { en: "You're ready!",     ar: 'أنت جاهز!' },
  onbAllSet:     { en: "You're all set!",   ar: 'أنت جاهز!' },
  onbReadySub:   { en: 'Start learning and track your progress.', ar: 'ابدأ التعلّم وتتبّع تقدّمك.' },
  onbStartNow:   { en: 'Start Now',         ar: 'ابدأ الآن' },
  onbStartLearning: { en: 'Start Learning', ar: 'ابدأ التعلم' },
  onbStepOf:     { en: 'Step',              ar: 'الخطوة' },
  onbOf:         { en: 'of',                ar: 'من' },
  onbContinue:   { en: 'Continue',         ar: 'متابعة' },
  onbGrade10:    { en: 'Grade 10',          ar: 'الصف العاشر' },
  onbGrade11:    { en: 'Grade 11',          ar: 'الصف الحادي عشر' },
  onbGrade12:    { en: 'Grade 12 (Tawjihi)', ar: 'الصف الثاني عشر (توجيهي)' },
  onbSubjectMath:{ en: 'Mathematics',       ar: 'الرياضيات' },
  onbSubjectSci: { en: 'Science',           ar: 'العلمي' },
  onbSubjectLit: { en: 'Literary',           ar: 'الأدبي' },
  // Legacy onboarding keys (kept for compatibility)
  onbTitle0:   { en: 'What is your name?',    ar: 'ما اسمك؟' },
  onbTitle1:   { en: 'What is your email?',   ar: 'ما بريدك الإلكتروني؟' },
  onbTitle2:   { en: 'Create a password',     ar: 'أنشئ كلمة مرور' },
  onbSub0:     { en: "Hi! I'm your math coach. What's your name?", ar: 'مرحباً! أنا مدرّسك الذكي. ما اسمك؟' },
  onbSub1:     { en: "We'll use this to save your progress.", ar: 'سنستخدم هذا لحفظ تقدّمك.' },
  onbSub2:     { en: 'Keep it safe! Min 6 characters.',  ar: 'اختر كلمة مرور قوية! 6 أحرف على الأقل.' },
  onbPh0:      { en: 'Your name',             ar: 'اسمك' },
  onbPh1:      { en: 'email@example.com',     ar: 'example@email.com' },
  onbPh2:      { en: 'Min 6 characters',      ar: '6 أحرف على الأقل' },
  aiCoach:     { en: "I'm your AI Math Coach", ar: 'أنا مدرّسك الذكي للرياضيات' },

  // Home
  goodMorning: { en: 'Good morning,',   ar: 'صباح الخير،' },
  goodAfternoon:{ en: 'Good afternoon,',ar: 'مساء الخير،' },
  goodEvening: { en: 'Good evening,',   ar: 'مساء النور،' },
  scheduled:   { en: '1 lesson scheduled today', ar: 'درس مقرر اليوم' },
  todayPlan:   { en: "Today's Plan",    ar: 'خطة اليوم' },
  coachName:   { en: 'Coach Nour',      ar: 'المدرب نور' },
  coachMsg:    { en: "Here are today's activities.", ar: 'إليك أنشطة اليوم.' },
  warmup:      { en: 'DAILY WARMUP', ar: 'تمرين اليوم' },
  tapReveal:   { en: 'Tap to reveal answer', ar: 'اضغط لإظهار الجواب' },
  lessonsLabel:{ en: 'LESSONS',      ar: 'الدروس' },
  inProgress:  { en: 'IN PROGRESS',    ar: 'جارٍ' },
  yourJourney: { en: 'CURRICULUM', ar: 'المنهج الدراسي' },
  keepGoing:   { en: 'Keep Going!',     ar: 'استمر في التقدم!' },
  journeySub:  { en: 'Track your progress through the full curriculum', ar: 'تتبّع تقدّمك عبر المنهج كاملًا' },
  stats:       { en: 'STATS',           ar: 'الإحصائيات' },
  studyTime:   { en: 'Study time',      ar: 'وقت الدراسة' },
  questions:   { en: 'Questions',       ar: 'الأسئلة' },
  accuracy:    { en: 'Accuracy',        ar: 'الدقة' },

  // Curriculum
  semester1:   { en: 'Semester 1',      ar: 'الفصل الأول' },
  semester2:   { en: 'Semester 2',      ar: 'الفصل الثاني' },
  journeyTitle:{ en: 'Curriculum',      ar: 'المنهج الدراسي' },
  myJourney:   { en: 'My Curriculum',   ar: 'منهجي' },
  myJourneySub: { en: 'View your curriculum and progress', ar: 'اعرض المنهج وتقدّمك' },
  openCurriculum: { en: 'Open Curriculum', ar: 'افتح المنهج' },
  startNext:   { en: 'Start Next Activity', ar: 'ابدأ النشاط التالي' },
  onARoll:     { en: "You're on a roll!", ar: 'أنت في قمة تألقك!' },
  examPrep:    { en: 'EXAM PREPARATION', ar: 'التحضير للامتحانات' },
  profileExamPrep: { en: 'Exam Prep',   ar: 'التحضير للامتحان' },
  examTawjihi: { en: 'Tawjihi Exams →', ar: 'امتحانات التوجيهي ←' },
  lessonsDone: { en: 'lessons',          ar: 'دروس' },

  // Profile (premium layout)
  grade12Tawjihi: { en: 'Grade 12 — Tawjihi', ar: 'الصف 12 — توجيهي' },
  premium:     { en: 'Premium',          ar: 'مميز' },
  free:        { en: 'Free',             ar: 'مجاني' },
  yourSubscription: { en: 'Your Subscription', ar: 'اشتراكك' },
  inviteFriends: { en: 'Invite Friends', ar: 'دعوة أصدقاء' },
  totalStudyHours: { en: 'Study hours',  ar: 'ساعات الدراسة' },
  currentStreak: { en: 'Streak',         ar: 'السلسلة' },
  overallAccuracy: { en: 'Accuracy',    ar: 'الدقة' },

  // Practice
  practiceTitle:{ en: 'Practice',       ar: 'التمارين' },
  qDone:       { en: 'questions done',  ar: 'سؤال تم' },
  searchTopics:{ en: 'Search topics...', ar: 'ابحث عن موضوع...' },
  dailyChal:   { en: 'DAILY CHALLENGE', ar: 'تحدي اليوم' },
  resetsIn:    { en: 'Resets in 8h',    ar: 'يُجدَّد خلال 8 ساعات' },
  dailyDecompose: { en: 'Decompose into partial fractions:', ar: 'حلّل إلى كسور جزئية:' },
  byTopic:     { en: 'PRACTICE BY TOPIC', ar: 'تمرّن حسب الموضوع' },
  topicsLabel: { en: 'TOPICS',          ar: 'مواضيع' },
  examPractice:{ en: 'EXAM PRACTICE',   ar: 'تمرّن على الامتحانات' },
  weakAreas:   { en: 'WEAK AREAS',      ar: 'نقاط الضعف' },
  reviewMist:  { en: 'Review your mistakes', ar: 'راجع أخطاءك' },
  mistakesSub: { en: 'Topics where you scored below 70%', ar: 'مواضيع حصلت فيها على أقل من 70%' },
  fullExam:    { en: 'Full Exam',        ar: 'امتحان كامل' },
  hrs:         { en: '2hrs',            ar: 'ساعتان' },
  chapAll:     { en: 'All',             ar: 'الكل' },
  chapAlg:     { en: 'Algebra',         ar: 'الجبر' },
  chapTrig:    { en: 'Trig',            ar: 'المثلثات' },
  chapCalc:    { en: 'Calculus',        ar: 'التفاضل' },
  chapComp:    { en: 'Complex',         ar: 'مركبة' },
  chapInt:     { en: 'Integration',     ar: 'التكامل' },
  easy:        { en: 'easy',            ar: 'سهل' },
  medium:      { en: 'medium',          ar: 'متوسط' },
  hard:        { en: 'hard',            ar: 'صعب' },

  // Settings
  settings:    { en: 'Settings',        ar: 'الإعدادات' },
  accountDets: { en: 'ACCOUNT DETAILS', ar: 'بيانات الحساب' },
  notifications:{ en: 'NOTIFICATIONS',  ar: 'الإشعارات' },
  dailyRem:    { en: 'Daily Study Reminders', ar: 'تذكيرات الدراسة اليومية' },
  studySettings:{ en: 'STUDY SETTINGS', ar: 'إعدادات الدراسة' },
  stepByStep:  { en: 'Show Step-by-Step Solutions', ar: 'عرض الحلول خطوة بخطوة' },
  listenTutor: { en: 'Listen to Tutor Guidance', ar: 'الاستماع إلى توجيهات المدرب' },
  autoplay:    { en: 'Autoplay Next Lesson', ar: 'تشغيل الدرس التالي تلقائياً' },
  celebrate:   { en: 'Celebrate High Scores (90%+)', ar: 'احتفل بالنتائج العالية (90%+)' },
  saveBookmarks:{ en: 'Save Bookmarks Automatically', ar: 'حفظ الإشارات المرجعية تلقائياً' },
  askRatings:  { en: 'Ask for Ratings & Feedback', ar: 'طلب التقييمات والملاحظات' },
  appLanguage: { en: 'APP LANGUAGE',    ar: 'لغة التطبيق' },
  languageLabel:{ en: 'Language',       ar: 'اللغة' },
  accountMgmt: { en: 'ACCOUNT MANAGEMENT', ar: 'إدارة الحساب' },
  logOut:      { en: 'Log Out',         ar: 'تسجيل الخروج' },
  deleteAccount:{ en: 'Delete Your Account', ar: 'حذف الحساب' },
  version:     { en: 'Version 1.0.0',   ar: 'الإصدار 1.0.0' },
  time:        { en: 'Time',            ar: 'الوقت' },
  nameLabel:   { en: 'Name',            ar: 'الاسم' },
  emailLabel:  { en: 'Email',           ar: 'البريد' },
  phoneLabel:  { en: 'Phone',           ar: 'الهاتف' },
  addPhone:    { en: 'Add phone number', ar: 'أضف رقم الهاتف' },
  demoUser:   { en: 'Demo User',       ar: 'مستخدم تجريبي' },
  reminderTime: { en: '9:00 AM',        ar: '9:00 ص' },
  langEn:     { en: 'English',          ar: 'English' },
  langAr:     { en: 'Arabic',           ar: 'Arabic' },
  deleteTitle: { en: 'Delete Your Account', ar: 'حذف حسابك' },
  deleteMsg:   { en: 'Are you sure? This action cannot be undone.', ar: 'هل أنت متأكد؟ لا يمكن التراجع عن هذا الإجراء.' },
  deleteConfirm:{ en: 'Delete',         ar: 'حذف' },
  connectSocial: { en: 'CONNECT ON SOCIAL MEDIA', ar: 'وسائل التواصل الاجتماعي' },
  socialInstagram: { en: 'Instagram',  ar: 'إنستغرام' },
  socialYouTube:   { en: 'YouTube',    ar: 'يوتيوب' },
  socialFacebook:  { en: 'Facebook',   ar: 'فيسبوك' },
  socialTwitter:   { en: 'Twitter / X', ar: 'تويتر / X' },
  socialTikTok:    { en: 'TikTok',     ar: 'تيك توك' },
  cancelLabel: { en: 'Cancel',          ar: 'إلغاء' },
  weLikeToHearFromYou: { en: "We'd like to hear from you", ar: 'نود أن نسمع منك' },
  sendFeedback: { en: 'Send Feedback', ar: 'أرسل ملاحظاتك' },
  rateTheApp:   { en: 'Rate the App',   ar: 'قيّم التطبيق' },
  supportTitle: { en: 'Support & Help', ar: 'الدعم والمساعدة' },
  supportHeroTitle: { en: 'How can we help?', ar: 'كيف يمكننا مساعدتك؟' },
  supportHeroSub: { en: 'We usually reply within one business day', ar: 'نرد عادةً خلال يوم عمل واحد' },
  supportContactEmail: { en: 'Email', ar: 'البريد' },
  supportContactWebsite: { en: 'Website', ar: 'الموقع' },
  supportContactTerms: { en: 'Terms', ar: 'الشروط' },
  supportFaqTitle: { en: 'FREQUENTLY ASKED QUESTIONS', ar: 'الأسئلة الشائعة' },
  supportMessageTitle: { en: 'SEND A MESSAGE', ar: 'أرسل رسالة' },
  supportSubjectPlaceholder: { en: 'Subject (optional)', ar: 'الموضوع (اختياري)' },
  supportMessagePlaceholder: { en: 'Write your message here...', ar: 'اكتب رسالتك هنا...' },
  supportOpenMail: { en: 'Open in Mail', ar: 'فتح في البريد' },
  supportReadyInMail: { en: 'Ready in Mail', ar: 'جاهزة في البريد' },
  supportSendToSupport: { en: 'Send to Support', ar: 'إرسال للدعم' },
  supportDirectSubject: { en: 'SnapMath Support Request', ar: 'استفسار عن SnapMath' },
  supportComposerSubject: { en: 'Support request from SnapMath Academy', ar: 'طلب دعم من SnapMath Academy' },
  supportEmptyMessageTitle: { en: 'Empty Message', ar: 'الرسالة فارغة' },
  supportEmptyMessageBody: { en: 'Please write your message first.', ar: 'يرجى كتابة رسالتك أولاً.' },
  supportMailOpenErrorTitle: { en: 'Cannot Open Mail', ar: 'تعذر فتح البريد' },
  supportMailOpenErrorBody: { en: 'Email us directly at: {{email}}', ar: 'راسلنا مباشرة على: {{email}}' },
  supportMailOpenedTitle: { en: 'Mail opened', ar: 'فتحنا البريد' },
  supportMailOpenedBody: { en: 'We prepared your message in the Mail app. Send it there and it will go directly to support.', ar: 'جهزنا رسالتك داخل تطبيق البريد. أرسلها من هناك ليصل الطلب مباشرة إلى فريق الدعم.' },
  supportMailUnavailableTitle: { en: 'Mail app unavailable', ar: 'تعذر فتح البريد' },
  supportMailUnavailableBody: { en: 'We copied the support email and message to your clipboard. Paste it into any mail app and send it to support.', ar: 'نسخنا البريد والرسالة إلى الحافظة. الصقها في أي تطبيق بريد وأرسلها إلى فريق الدعم.' },

  // Parents dashboard (view-only)
  parentsTitle:     { en: 'Parents',              ar: 'أولياء الأمور' },
  childName:        { en: "Child's progress",     ar: 'تقدّم الطالب' },
  weeklyStudyTime:  { en: 'Weekly study time',    ar: 'وقت الدراسة الأسبوعي' },
  lessonsThisWeek:  { en: 'Lessons this week',    ar: 'الدروس هذا الأسبوع' },
  accuracyPct:      { en: 'Accuracy',             ar: 'الدقة' },
  strengths:        { en: 'Strengths',            ar: 'نقاط القوة' },
  weaknesses:       { en: 'Weaknesses',           ar: 'نقاط الضعف' },
  upcomingTopics:  { en: 'Upcoming topics',       ar: 'المواضيع القادمة' },
  examReadiness:   { en: 'Exam readiness',        ar: 'جاهزية الامتحان' },
  dailyStreak:     { en: 'Daily streak',         ar: 'سلسلة الأيام' },
  detailedReport:  { en: 'Detailed Report',       ar: 'تقرير مفصل' },
  basedOnProgress: { en: 'Based on your progress', ar: 'بناءً على تقدّمك' },
  mins:             { en: 'min',                  ar: 'دق' },
  performanceReport: { en: 'Performance Report', ar: 'تقرير الأداء' },
  shareReport:      { en: 'Share Report',        ar: 'مشاركة التقرير' },
  studyHoursThisWeek: { en: 'Study Hours',       ar: 'ساعات الدراسة' },
  questionsAnswered: { en: 'Questions Answered',  ar: 'الأسئلة المجابة' },
  totalHours:       { en: 'hrs',                 ar: 'س' },
  streakDays:       { en: 'day streak',          ar: 'أيام متتالية' },
  estimatedDate:    { en: 'Est.',                 ar: 'تقريبي' },

  // Subscription
  subTitle:           { en: 'Subscription',        ar: 'الاشتراك' },
  changeYourPlan:     { en: 'Change Your Plan',    ar: 'غيّر خطتك' },
  planStandard:       { en: 'Standard',            ar: 'الأساسية' },
  planTawjihi:        { en: 'Tawjihi',             ar: 'التوجيهي' },
  featureAccessLessons:{ en: 'Access to lessons',  ar: 'الوصول إلى الدروس' },
  featureUnlimitedAI: { en: 'Unlimited AI chat',    ar: 'محادثة ذكاء اصطناعي غير محدودة' },
  featureAllFeatures: { en: 'All features',         ar: 'جميع المميزات' },
  billingMonthly:     { en: 'Monthly',             ar: 'شهري' },
  billingAnnual:      { en: 'Annual',               ar: 'سنوي' },
  billingOnetime:     { en: 'One-time',            ar: 'دفعة واحدة' },
  price29Month:       { en: '29 JOD / month',      ar: '29 دينار / شهر' },
  price199Year:       { en: '199 JOD / year',      ar: '199 دينار / سنة' },
  price79:            { en: '79 JOD',              ar: '79 دينار' },
  save50:             { en: 'SAVE 50%',            ar: 'وفّر 50%' },
  changeSubscription: { en: 'Change Subscription', ar: 'تغيير الاشتراك' },
  restorePurchases:   { en: 'Restore purchases',   ar: 'استعادة المشتريات' },
  terms:              { en: 'Terms',                ar: 'الشروط' },
  privacy:            { en: 'Privacy',             ar: 'الخصوصية' },
  currentPlan:        { en: 'CURRENT',             ar: 'الحالي' },
  standardPlan:       { en: 'Standard Plan',       ar: 'الخطة الأساسية' },
  renewsDate:         { en: 'Renews Jan 15, 2026', ar: 'تجديد في 15 كانون الثاني 2026' },

  // Lesson screen
  lessonTitle:       { en: 'Lesson',              ar: 'الدرس' },
  videoLesson:       { en: 'Video Lesson',         ar: 'درس فيديو' },
  lessonTopicPartialFractions: { en: 'Partial Fractions', ar: 'الكسور الجزئية' },
  masterThisTopic:   { en: 'Master this topic step by step', ar: 'أتقن هذا الموضوع خطوة بخطوة' },
  decompositionPreview: { en: 'DECOMPOSITION PREVIEW', ar: 'معاينة التحليل' },
  stageLabelPrefix:  { en: 'Stage ',               ar: 'المرحلة ' },
  stageVideo:        { en: 'Video',                ar: 'فيديو' },
  stageGuided:       { en: 'Guided',               ar: 'موجّه' },
  stageSolo:         { en: 'Solo',                 ar: 'فردي' },
  stageVoice:        { en: 'Voice',                ar: 'صوت' },
  stageMaster:       { en: 'Master',               ar: 'إتقان' },

  // Question count (Western numerals + label)
  questionShort:    { en: 'Q',                    ar: 'سؤال' },

  // Groups
  studyGroups:    { en: 'Study Groups',         ar: 'مجموعات الدراسة' },
  learnTogether:  { en: 'Learn together',       ar: 'تعلّم معاً' },
  myGroups:       { en: 'My Groups',            ar: 'مجموعاتي' },
  discover:       { en: 'Discover',              ar: 'اكتشف' },
  online:         { en: 'online',                ar: 'متصل' },
  members:        { en: 'members',               ar: 'أعضاء' },
  activeStudySession: { en: 'Active Study Session', ar: 'جلسة دراسة نشطة' },
  enter:          { en: 'Enter →',               ar: '← ادخل' },
  join:           { en: 'Join',                 ar: 'انضم' },
  noGroupsYet:    { en: "You haven't joined any groups yet", ar: 'لم تنضم لأي مجموعة بعد' },
  discoverGroups: { en: 'Discover Groups',       ar: 'اكتشف المجموعات' },
  joinWithCode:   { en: 'Join with Code',        ar: 'انضم برمز' },
  enterGroupCode: { en: 'Enter the group code',  ar: 'أدخل رمز المجموعة' },
  createGroup:    { en: 'Create Group',          ar: 'إنشاء مجموعة' },
  groupName:      { en: 'Group name',            ar: 'اسم المجموعة' },
  topic:          { en: 'Topic',                 ar: 'الموضوع' },
  create:         { en: 'Create',               ar: 'إنشاء' },
  typeMessage:   { en: 'Type a message...',    ar: 'اكتب رسالة...' },

  // Auth, onboarding, and home polish
  authSignInTab: { en: 'Sign In', ar: 'تسجيل الدخول' },
  authSignUpTab: { en: 'Sign Up', ar: 'حساب جديد' },
  authFullName: { en: 'Full Name', ar: 'الاسم الكامل' },
  authYourNamePlaceholder: { en: 'Your name', ar: 'اسمك' },
  authEmailPlaceholder: { en: 'you@example.com', ar: 'بريدك@مثال.com' },
  authPasswordPlaceholder: { en: '••••••••', ar: '••••••••' },
  authCreateAccount: { en: 'Create Account', ar: 'إنشاء حساب' },
  authExploreGuest: { en: 'Continue as Guest', ar: 'متابعة كضيف' },
  authNoAccountPrefix: { en: "Don't have an account? ", ar: 'ليس لديك حساب؟ ' },
  authNoAccountAction: { en: 'Sign Up', ar: 'سجّل الآن' },
  authHasAccountPrefix: { en: 'Already have an account? ', ar: 'لديك حساب بالفعل؟ ' },
  authHasAccountAction: { en: 'Sign In', ar: 'سجّل الدخول' },
  authMissingEmail: { en: 'Please enter your email', ar: 'يرجى إدخال البريد الإلكتروني' },
  authShortPassword: { en: 'Password must be at least 6 characters', ar: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل' },
  authMissingName: { en: 'Please enter your name', ar: 'يرجى إدخال اسمك' },
  authGenericError: { en: 'Something went wrong. Please try again.', ar: 'حدث خطأ. حاول مرة أخرى.' },
  authIncorrectCredentials: { en: 'Incorrect email or password', ar: 'البريد الإلكتروني أو كلمة المرور غير صحيحة' },
  authEmailInUse: { en: 'Email already in use', ar: 'البريد الإلكتروني مستخدم بالفعل' },
  authInvalidEmail: { en: 'Invalid email address', ar: 'البريد الإلكتروني غير صالح' },
  authNetworkError: { en: 'Network error. Check your connection.', ar: 'تعذر الاتصال. تحقق من الإنترنت.' },
  onboardingWelcomeTitle: { en: 'Welcome to SnapMath', ar: 'أهلاً بك في SnapMath' },
  onboardingWelcomeSub: { en: 'Choose your grade level to get started', ar: 'اختر صفك الدراسي للبدء' },
  onboardingGradeTawjihiSub: { en: 'Prepare for Tawjihi exam', ar: 'استعد للتوجيهي' },
  onboardingNameTitle: { en: "What's your name?", ar: 'ما اسمك؟' },
  onboardingNameSub: { en: "We'll personalize your learning journey", ar: 'سنخصّص رحلتك التعليمية لك' },
  onboardingNamePlaceholder: { en: 'Your name', ar: 'اكتب اسمك هنا' },
  onboardingAvatarColor: { en: 'Pick your avatar colour', ar: 'اختر لون أفاتارك' },
  onboardingGoalTitle: { en: 'Set your daily goal', ar: 'ما هدفك اليومي؟' },
  onboardingGoalSub: { en: 'Consistency beats intensity - start small', ar: 'الاتساق أهم من الكثافة' },
  onboardingStartTitle: { en: 'Where do you want to start?', ar: 'من أين تبدأ؟' },
  onboardingStartSub: { en: 'You can change this anytime in your Journey', ar: 'يمكنك تغيير هذا لاحقاً في أي وقت' },
  onboardingStepGrade: { en: 'Your Grade', ar: 'اختر صفك' },
  onboardingStepAbout: { en: 'About You', ar: 'عرّف عن نفسك' },
  onboardingStepGoal: { en: 'Daily Goal', ar: 'هدفك اليومي' },
  onboardingStepFirstUnit: { en: 'First Unit', ar: 'أول وحدة' },
  homeGreeting: { en: 'Hey{{name}}! 👋', ar: '👋 مرحباً{{name}}' },
  homeLevelProgress: { en: 'Lv {{level}} · {{xp}} XP to next level', ar: 'المستوى {{level}} · يتبقى {{xp}} XP للمستوى التالي' },
  homeCoachPlan: { en: "Hey{{name}}! Here is today's {{grade}} math plan. Focus on one lesson and one practice set.", ar: 'هذه خطة الرياضيات لليوم. ركز على درس واحد ومجموعة تدريب واحدة.' },
  homeMathScanSub: { en: 'Snap any problem for step-by-step guidance', ar: 'صوّر أي مسألة واحصل على إرشاد خطوة بخطوة' },
  homePracticeSet: { en: 'Practice Set', ar: 'مجموعة تدريب' },
  homeFunctionsAlgebra: { en: 'Functions and Algebraic Expressions', ar: 'الدوال والتعابير الجبرية' },
  homeTrigIdentities: { en: 'Trig Identities and Equations', ar: 'متطابقات ومعادلات مثلثية' },
  homeJourneyMeta: { en: 'Grade 12 · All Units', ar: 'الصف 12 · كل الوحدات' },
  homeLessonsCount: { en: '{{completed}}/{{total}} lessons', ar: '{{completed}}/{{total}} درس' },
  homeNew: { en: 'NEW', ar: 'جديد' },

  // Practice and library
  practiceDailyChallengeLabel: { en: 'DAILY CHALLENGE', ar: 'تحدي اليوم' },
  practiceDailyPrompt: { en: 'Decompose into partial fractions:', ar: 'حلّل إلى كسور جزئية:' },
  practiceResetsSoon: { en: 'Resets in 8h', ar: 'يُجدَّد خلال 8 ساعات' },
  practiceStartBtn: { en: 'Start', ar: 'ابدأ' },
  practiceQuickSolveTitle: { en: 'Quick Solve', ar: 'حل سريع' },
  practiceQuickSolveSub: { en: 'Solve and get scored', ar: 'حل واحصل على النتيجة' },
  practiceMathLibraryTitle: { en: 'Math Library', ar: 'مكتبة الرياضيات' },
  practiceMathLibrarySub: { en: 'Practice specific topics', ar: 'تدرب على مواضيع محددة' },
  practiceExamSimTitle: { en: 'Exam Simulators', ar: 'محاكاة الاختبارات' },
  practiceExamSimSub: { en: 'Full-length and quick mock exams', ar: 'امتحانات تدريبية كاملة وسريعة' },
  practiceBookmarksTitle: { en: 'Bookmarks', ar: 'الإشارات المرجعية' },
  practiceBookmarksSaved: { en: '{{count}} saved', ar: '{{count}} محفوظة' },
  practiceBookmarksEmpty: { en: 'None saved yet', ar: 'لا توجد إشارات بعد' },
  practiceScanPill: { en: 'MathScan - Snap a problem', ar: 'MathScan - صوّر مسألتك' },
  soundLibraryTitle: { en: 'Math Library', ar: 'مكتبة الرياضيات' },
  soundLibraryCoreTopics: { en: 'Core Topics', ar: 'مواضيع أساسية' },
  soundLibraryAdvancedTopics: { en: 'Advanced Topics', ar: 'مواضيع متقدمة' },
  soundLibrarySemester1Topics: { en: 'Semester 1 Topics', ar: 'مواضيع الفصل الأول' },
  soundLibrarySemester2Topics: { en: 'Semester 2 Topics', ar: 'مواضيع الفصل الثاني' },
  soundLibraryTopicCount: { en: '{{count}} topics', ar: '{{count}} مواضيع' },

  // Curriculum
  curriculumTitle: { en: 'Curriculum', ar: 'المنهج الدراسي' },
  curriculumGrade12Math: { en: 'Grade 12 Mathematics', ar: 'رياضيات الصف 12' },
  curriculumOverviewSummary: { en: '{{units}} units · {{lessons}} lessons · 2 semesters', ar: '{{units}} وحدات · {{lessons}} درساً · فصلان' },
  curriculumOverallProgress: { en: 'Overall progress', ar: 'التقدم الإجمالي' },
  curriculumUnits: { en: 'Units', ar: 'وحدة' },
  curriculumLessons: { en: 'Lessons', ar: 'درس' },
  curriculumDone: { en: 'Done', ar: 'مكتملة' },
  curriculumActive: { en: 'Active', ar: 'جارية' },
  curriculumPercentComplete: { en: '{{progress}}% complete', ar: '{{progress}}% مكتمل' },
  curriculumLocked: { en: 'Locked', ar: 'مقفل' },
  curriculumNotStarted: { en: 'Not started', ar: 'لم تبدأ بعد' },
  curriculumBonusLockedTitle: { en: 'Bonus Content - Locked', ar: 'محتوى إضافي مقفل' },
  curriculumBonusLockedSub: { en: 'Complete 2 units to unlock', ar: 'أكمل وحدتين لفتح هذا المحتوى' },
  curriculumResourcesTitle: { en: 'Study Resources', ar: 'موارد الدراسة' },
  curriculumResourcesSub: { en: 'Live tools and references tied to the current Grade 12 bank', ar: 'أدوات ومراجع حية مرتبطة ببنك الصف 12 الحالي' },
  curriculumTextbook: { en: 'Jordanian Book', ar: 'الكتاب الأردني' },
  curriculumTextbookSub: { en: 'Open the built-in Semester 1 and Semester 2 workbooks', ar: 'افتح كتابي تمارين الفصل الأول والثاني المضمّنين داخل التطبيق' },
  textbookTitle: { en: 'Jordanian Book', ar: 'الكتاب الأردني' },
  textbookSubtitle: { en: 'Grade 12 Semester 1 and Semester 2 workbooks inside the app', ar: 'كتبا تمارين الصف 12 للفصلين الأول والثاني داخل التطبيق' },
  textbookBuiltInBadge: { en: 'Built in app', ar: 'مضمّن داخل التطبيق' },
  textbookWorkbookCollectionBody: { en: 'Choose Semester 1 or Semester 2 below to open the Jordanian workbook directly inside the app.', ar: 'اختر الفصل الأول أو الثاني في الأسفل لفتح كتاب التمارين الأردني مباشرة داخل التطبيق.' },
  textbookOpenExternal: { en: 'Open in browser', ar: 'افتح في المتصفح' },
  textbookReload: { en: 'Reload', ar: 'إعادة التحميل' },
  textbookLoading: { en: 'Preparing workbook PDF...', ar: 'يجري تجهيز ملف كتاب التمارين...' },
  textbookLoadErrorTitle: { en: 'Could not open this workbook yet', ar: 'تعذّر فتح كتاب التمارين حالياً' },
  textbookLoadErrorBody: { en: 'Try reloading this built-in PDF. If the problem continues, reopen the screen and try again.', ar: 'حاول إعادة تحميل ملف الـ PDF المضمّن. وإذا استمرت المشكلة فأعد فتح الشاشة ثم جرّب مرة أخرى.' },
  textbookEmptyTitle: { en: 'Textbook link not added yet', ar: 'لم تتم إضافة رابط الكتاب بعد' },
  textbookEmptyBody: { en: 'Add `expo.extra.textbookPdfUrl` in app config to open the official PDF here.', ar: 'أضف `expo.extra.textbookPdfUrl` في إعدادات التطبيق لفتح ملف PDF الرسمي هنا.' },
  textbookBackToCurriculum: { en: 'Back to curriculum', ar: 'العودة إلى المنهج' },

  // Settings data/sync status
  settingsProgressData: { en: 'PROGRESS & DATA', ar: 'التقدم والبيانات' },
  settingsSaveMode: { en: 'Save Mode', ar: 'طريقة الحفظ' },
  settingsLocalOnly: { en: 'Local Only', ar: 'محلي فقط' },
  settingsLocalCloud: { en: 'Local + Cloud', ar: 'محلي + سحابي' },
  settingsWhatGetsSaved: { en: 'What gets saved?', ar: 'ما الذي يتم حفظه؟' },
  settingsSavedItems: { en: 'XP + Results + Bookmarks', ar: 'XP + نتائج + إشارات' },
  settingsLessonMastery: { en: 'Lesson Mastery', ar: 'إتقان الدروس' },
  settingsBackedUp: { en: 'Backed up to cloud', ar: 'يُنسخ احتياطياً' },
  settingsOnDevice: { en: 'Saved on this device', ar: 'يُحفظ على هذا الجهاز' },
  settingsTimedSessions: { en: 'Timed Sessions', ar: 'الجلسات الموقّتة' },
  settingsInsideExamSim: { en: 'Inside Exam Simulators', ar: 'ضمن محاكاة الاختبارات' },
  settingsSyncStatus: { en: 'Sync Status', ar: 'المزامنة' },
  settingsAutoSync: { en: 'Auto-sync enabled', ar: 'تتم المزامنة تلقائياً' },
  settingsSignInForCloud: { en: 'Sign in for cloud backup', ar: 'سجّل الدخول للنسخ السحابي' },
  settingsLogoutErrorTitle: { en: 'Unable to log out', ar: 'تعذر تسجيل الخروج' },
  settingsLogoutErrorBody: { en: 'Please try again in a moment.', ar: 'حاول مرة أخرى بعد قليل.' },

  // Referral
  referralTitle: { en: 'Refer Friends', ar: 'دعوة الأصدقاء' },
  referralHeroTitle: { en: 'Earn XP by Inviting Friends', ar: 'اربح XP بدعوة الأصدقاء' },
  referralHeroSub: { en: 'Share SnapMath Academy with classmates and unlock referral XP milestones as they join you.', ar: 'شارك SnapMath Academy مع زملائك وافتح مكافآت XP الخاصة بالإحالة كلما انضم مزيد من الأصدقاء.' },
  referralReferred: { en: 'Referrals', ar: 'الإحالات' },
  referralEarned: { en: 'XP Unlocked', ar: 'XP المكتسب' },
  referralToNextBonus: { en: 'To next milestone', ar: 'حتى المكافأة التالية' },
  referralInviteLink: { en: 'Your invite link', ar: 'رابط الدعوة الخاص بك' },
  referralCopy: { en: 'Copy', ar: 'نسخ' },
  referralCopied: { en: 'Done!', ar: 'تم!' },
  referralShareLink: { en: 'Share Your Link', ar: 'مشاركة الرابط' },
  referralShareMessage: { en: 'Join me on SnapMath Academy for Grade 12 math: https://{{link}}', ar: 'انضم إليّ في SnapMath Academy للصف 12: https://{{link}}' },
  referralProgressTo: { en: 'Progress to: {{label}}', ar: 'التقدم نحو: {{label}}' },
  referralMilestoneReached: { en: '🏆 Milestone reached!', ar: '🏆 أكملت هذا المستوى!' },
  referralToNextCount: { en: '{{count}} more referrals to next bonus', ar: '{{count}} دعوات متبقية للمكافأة التالية' },
  referralToNextSingle: { en: '{{count}} more referral to next bonus', ar: '{{count}} دعوة متبقية للمكافأة التالية' },
  referralLegend: { en: 'Legend', ar: 'مفتاح' },
  referralXpMilestones: { en: 'XP Milestones', ar: 'مكافآت XP' },
  referralDemo: { en: 'Simulate a referral (demo)', ar: 'محاكاة إحالة جديدة (للتجربة)' },
  referralHowItWorks: { en: 'How it works', ar: 'كيف يعمل؟' },
  referralTerms: { en: 'By participating in the referral program, you agree to the Terms and Conditions.', ar: 'بالمشاركة في برنامج الإحالة، أوافق على الشروط والأحكام.' },
  referralMilestoneTitle: { en: '🎉 Milestone Reached!', ar: '🎉 مبروك!' },
  referralMilestoneBody: { en: 'You unlocked "{{label}}"! +{{bonus}} XP bonus awarded.', ar: 'لقد حققت "{{label}}"! ربحت {{bonus}} نقطة XP إضافية.' },
  referralStep1Title: { en: 'Share your link', ar: 'شارك رابطك' },
  referralStep1Sub: { en: 'Copy and send it to friends anywhere', ar: 'انسخ الرابط وأرسله لأصدقائك في أي مكان' },
  referralStep2Title: { en: 'Friends join the app', ar: 'ينضم أصدقاؤك إلى التطبيق' },
  referralStep2Sub: { en: 'They open SnapMath Academy from your shared link and start studying Grade 12 math.', ar: 'يفتحون SnapMath Academy من الرابط الذي شاركته ويبدؤون دراسة رياضيات الصف 12.' },
  referralStep3Title: { en: 'Milestones unlock XP', ar: 'المراحل تفتح مكافآت XP' },
  referralStep3Sub: { en: 'As your referral count grows, milestone XP bonuses become available on your account.', ar: 'كلما زاد عدد الإحالات لديك أصبحت مكافآت XP المرحلية متاحة في حسابك.' },
  referralStep4Title: { en: 'Keep building your streak', ar: 'واصل بناء تقدمك' },
  referralStep4Sub: { en: 'Hit 1, 3, 5, 10, and 20 referrals to unlock bigger XP boosts.', ar: 'حقق 1 و3 و5 و10 و20 إحالة لتحصل على دفعات XP أكبر.' },
};

const interpolate = (template, values = {}) => {
  return String(template).replace(/\{\{(\w+)\}\}/g, (_, key) => {
    const value = values[key];
    return value === undefined || value === null ? '' : String(value);
  });
};

const LanguageContext = createContext({ lang: 'ar', setLang: () => {}, t: (/** @type {string} */ _key, _values = {}) => '', isAr: true });

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState('ar');

  useEffect(() => {
    AsyncStorage.getItem(LANG_KEY).then(v => {
      if (v === 'ar' || v === 'en') {
        setLangState(v);
      } else {
        setLangState('ar');
        AsyncStorage.setItem(LANG_KEY, 'ar').catch(() => null);
      }
    });
  }, []);

  const setLang = async (newLang) => {
    setLangState(newLang);
    await AsyncStorage.setItem(LANG_KEY, newLang);
  };

  const t = (key, values = {}) => {
    const entry = STRINGS[key];
    if (!entry) return interpolate(key, values);
    return interpolate(entry[lang] ?? entry.en ?? key, values);
  };

  const isAr = lang === 'ar';

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isAr }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useT() {
  return useContext(LanguageContext);
}
